name: Release

on:
  push:
    tags:
      - 'release/*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Lua compiler
      run: sudo apt-get -y install lua5.2

    - name: Set build variables
      run: echo "revision=${GITHUB_REF##*/}" >> ${GITHUB_ENV}

    - name: Make release package
      run: make package ZIPFILE="rotorflight-opentx-lua-${GITHUB_REF##*/}.zip"

    - name: Create Release
      run: |
        gh release create ${GITHUB_REF##refs/tags/} --notes-file "Release.md" --title "Rotorflight LUA Scripts Release ${GITHUB_REF##*/}" *.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

