name: Snapshot

on:
  push:
    tags:
      - 'snapshot/*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Lua compiler
      run: sudo apt-get -y install lua5.2

    - name: Set build variables
      run: echo "revision=${GITHUB_REF##*/}" >> ${GITHUB_ENV}

    - name: Make snapshot package
      run: make package ZIPFILE="rotorflight-lua-scripts-snapshot-${GITHUB_REF##*/}.zip"

    - name: Create Snapshot
      run: |
        gh release create ${GITHUB_REF##refs/tags/} --prerelease --notes-file "Snapshot.md" --title "Rotorflight LUA Scripts Snapshot ${GITHUB_REF##*/}" *.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

