name: Testing

on:
  push:
    tags:
      - 'testing/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Lua compiler
      run: sudo apt-get -y install lua5.2

    - name: Set build variables
      run: echo "revision=${GITHUB_REF##*/}" >> ${GITHUB_ENV}

    - name: Make test files
      run: make files VARIANT="test"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rotorflight-opentx-lua-testing-${{ env.revision }}
        path: ./test

    - name: Delete tag
      run: git push origin :${GITHUB_REF}
